list_of_titles = ['Acupuncturist',
    'Adjunct Professor',
    'Anesthesia Technician',
    'Anesthesiologist',
    'Assisted Living Administrator',
    'Associate Dentist',
    'Athletic Trainer',
    'Audiologist',
    'Behavioral Health Technician',
    'Behavioral Interventionist',
    'Behavioral Specialist',
    'Biomedical Equipment Technician',
    'Blood Bank Technologist',
    'CNA',
    'CRNA',
    'Cardiac Sonographer',
    'Cardiovascular Technologist',
    'Care Assistant',
    'Certified Dental Assistant',
    'Certified Medical Assistant',
    'Certified Medication Aide',
    'Certified Occupational Therapy Assistant',
    'Certified Ophthalmic Assistant',
    'Certified Pharmacy Technician',
    'Certified Surgical Technologist',
    'Child Psychiatrist',
    'Chiropractic Assistant',
    'Chiropractor',
    'Clinical Assistant',
    'Clinical Dietitian',
    'Clinical Medical Assistant',
    'Clinical Pharmacist',
    'Clinical Psychologist',
    'Clinical Research',
    'Clinical Research Coordinator',
    'Clinical Research Manager',
    'Clinical Specialist',
    'Clinician',
    'Contact Tracing',
    'Critical Care Technician',
    'Ct Technologist',
    'Cytotechnologist',
    'Dental',
    'Dental Assistant',
    'Dental Ceramist',
    'Dental Hygienist',
    'Dental Lab Technician',
    'Dental Technician',
    'Dentist',
    'Dermatologist',
    'Diabetes Educator',
    'Diagnostic Medical Sonographer',
    'Dialysis Rn',
    'Dialysis Technician',
    'Dietetic Technician',
    'Dietitian',
    'Direct Care Professional',
    'Doctor',
    'Dosimetrist',
    'Drug Safety Associate',
    'EMT',
    'Echocardiographer',
    'Ekg Technician',
    'Embryologist',
    'Emergency Department Technician',
    'Emergency Medical Technician',
    'Emergency Room Technician',
    'Emr Trainer',
    'Endocrinologist',
    'Endodontist',
    'Endoscopy Technician',
    'Environmental Health Specialist',
    'Er Rn',
    'Er Technician',
    'Family Physician',
    'Flight Paramedic',
    'Formulation Scientist',
    'General Dentist',
    'General Practitioner',
    'General Surgeon',
    'Genetic Counselor',
    'Gynecologist',
    'Health Aide',
    'Health Care Specialist',
    'Health Coach',
    'Health Inspector',
    'Health Specialist',
    'Health Technician',
    'Healthcare Management',
    'Hearing Aid Specialist',
    'Hearing Instrument Specialist',
    'Hemodialysis Technician',
    'Histology Technician',
    'Histotechnologist',
    'Home Health Aide',
    'Hospice Aide',
    'Hospital Pharmacist',
    'Hospitalist',
    'Hygienist',
    'Intervention Specialist',
    'LPN',
    'LVN',
    'Lab Assistant',
    'Laboratory Technologist',
    'Laser Technician',
    'Lead Pharmacy Technician',
    'MRI Technologist',
    'Mammography Technologist',
    'Medical Assistant',
    'Medical Doctor',
    'Medical Laboratory Technician',
    'Medical Laboratory Technologist',
    'Medical Liaison',
    'Medical Office Manager',
    'Medical Physicist',
    'Medical Scribe',
    'Medical Technician',
    'Medical Technologist',
    'Medical Transcriptionist',
    'Medication Technician',
    'Mental Health Assistant',
    'Mental Health Clinician',
    'Mental Health Counselor',
    'Mental Health Professional',
    'Mental Health Specialist',
    'Mental Health Technician',
    'Mental Health Therapist',
    'Mental Health Worker',
    'Mobile Phlebotomist',
    'Mri Technician',
    'Neurologist',
    'Neurosurgeon',
    'Nuclear Medicine Technologist',
    'Nuclear Pharmacist',
    'Nutrition Assistant',
    'Nutritionist',
    'Obstetrician',
    'Occupational Therapist',
    'Occupational Therapy Assistant',
    'Oncologist',
    'Oncology Pharmacist',
    'Ophthalmic Technician',
    'Ophthalmologist',
    'Optician',
    'Optometric Assistant',
    'Optometrist',
    'Optometrist Assistant',
    'Orderly',
    'Orthodontic Assistant',
    'Orthodontist',
    'Orthodontist Assistant',
    'Orthopedic Surgeon',
    'Orthopedic Technician',
    'Outpatient Therapist',
    'Pacu Rn',
    'Paramedic',
    'Pathologist',
    'Pathologist Assistant',
    'Patient Care Assistant',
    'Patient Care Manager',
    'Patient Care Specialist',
    'Patient Care Technician',
    'Patient Coordinator',
    'Patient Navigator',
    'Patient Sitter',
    'Patient Transport',
    'Patient Transporter',
    'Pediatric Dentist',
    'Pediatric Occupational Therapist',
    'Pediatrician',
    'Perfusionist',
    'Periodontist',
    'Personal Care Attendant',
    'Pharmaceutical Representative',
    'Pharmaceutical Sales',
    'Pharmacist',
    'Pharmacy Assistant',
    'Pharmacy Technician',
    'Phlebotomy',
    'Phlebotomy Supervisor',
    'Phlebotomy Technician',
    'Physical Therapist Assistant',
    'Physician',
    'Physician Assistant',
    'Physician Liaison',
    'Plastic Surgeon',
    'Podiatrist',
    'Primary Care Physician',
    'Psychiatric Technician',
    'Psychiatrist',
    'Psychologist',
    'Psychotherapist',
    'Radiation Therapist',
    'Radiologic Technologist',
    'Radiologist',
    'Radiology',
    'Radiology Manager',
    'Radiology Technologist',
    'Registered Behavior Technician',
    'Registered Dental Assistant',
    'Registered Dietitian',
    'Registered Pharmacist',
    'Registered Respiratory Therapist',
    'Rehab Technician',
    'Renal Dietitian',
    'Respiratory Care Practitioner',
    'Respiratory Therapist',
    'Retail Pharmacist',
    'Rn Supervisor',
    'Senior Pharmacy Technician',
    'Sleep Technician',
    'Sonographer',
    'Specimen Processor',
    'Speech Pathologist',
    'Staff Pharmacist',
    'Sterile Processing Technician',
    'Surgeon',
    'Surgical Assistant',
    'Surgical Technician',
    'Surgical Technologist',
    'Travel CNA',
    'Ultrasonographer',
    'Ultrasound Technician',
    'Ultrasound Technologist',
    'Urologist',
    'Vascular Surgeon',
    'Vascular Technician',
    'Vascular Technologist',
    'Veterinary Assistant',
    'Veterinary Technician',
    'Wic Nutritionist',
    'X Ray Technician']